In [1]:
import numpy as np

a=np.array(5)

print("Print A= ",a)

b=np.array([40,50,60])

print("Print B= ", b)

addition= np.add(a,b)

print("After Addition =", addition)

sub=np.subtract(b,a)

print("After Subtraction =",sub)

mul=np.multiply (a,b)

print("After Multiplcation =",mul)

div=np.divide (b,a)

print("After Division =",div)

div1=np.divide (b,5)

print("After Division =",div1)

Print A=  5
Print B=  [40 50 60]
After Addition = [45 55 65]
After Subtraction = [35 45 55]
After Multiplcation = [200 250 300]
After Division = [ 8. 10. 12.]
After Division = [ 8. 10. 12.]


In [2]:
#reciprocal

a= np.array([0.55,8.33,8,188])

print(a)

rec=np.reciprocal(a) 
print(rec)

[  0.55   8.33   8.   188.  ]
[1.81818182 0.12004802 0.125      0.00531915]


In [3]:
a=np.array([1000,10,100])

print(a)

pow=np.power(a,2)
print("after ^2 = ", pow)


b=np.array([2,1,3])

pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)


[1000   10  100]
after ^2 =  [1000000     100   10000]
after b array elements as ^ =  [1000000      10 1000000]


In [4]:
a= np.array ([40,70,30])
b= np.array ([4,6,5])

print("values of A=", a)
print("values of B=", b)

mm=np.mod(a,b)

rm=np.remainder(a,b)

print("values of MOD=", mm)
print("values of REMAINDER=", rm)

values of A= [40 70 30]
values of B= [4 6 5]
values of MOD= [0 4 0]
values of REMAINDER= [0 4 0]


In [5]:
a=np.array([0.6j, 3.6j,11, -2.7j])
print(a)

print("real=",np.real(a))

print("imaginary=",np.imag(a))

print("Conjugate=", np.conj(a))

[ 0.+0.6j  0.+3.6j 11.+0.j  -0.-2.7j]
real= [ 0.  0. 11. -0.]
imaginary= [ 0.6  3.6  0.  -2.7]
Conjugate= [ 0.-0.6j  0.-3.6j 11.-0.j  -0.+2.7j]


In [6]:
a=np.array ([2.0,3.9,433,0.87,28,30.8])

print(a)

print("after rounding up=", np.around(a))

print("after rounding up to 1st decimal value =", np.around(a,decimals=1))

[  2.     3.9  433.     0.87  28.    30.8 ]
after rounding up= [  2.   4. 433.   1.  28.  31.]
after rounding up to 1st decimal value = [  2.    3.9 433.    0.9  28.   30.8]


In [7]:
a=np.array ([-2.8,1.6,521,26.6,-5.53,63])

print(a)

print('\n')

print(np.floor(a))

print(np.ceil(a))

[ -2.8    1.6  521.    26.6   -5.53  63.  ]


[ -3.   1. 521.  26.  -6.  63.]
[ -2.   2. 521.  27.  -5.  63.]
