In [9]:
import numpy as npa 
npa= np.array([1, 2, 3])
print(npa)

[1 2 3]


In [14]:
import numpy as npp
a = npp.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [1]:
import numpy as np
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [2]:
import numpy as np
a=np.ones(2)
print(a)

[1. 1.]


In [4]:
import numpy as np
ab=np.empty(4)
print(ab)

[2.12199579e-314 1.29061821e-306 4.38730294e-321 1.95223613e-312]


In [5]:
import numpy as np
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [6]:
import numpy as np
a=np.arange(3,8,3)
print(a)

[3 6]


In [7]:
y = np.ones(4, dtype=int)
print(y)
y

[1 1 1 1]


array([1, 1, 1, 1])

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a)


a=np.delete(a, 2)
print(a)

[1 2 3 4 5 6 7 8]
[1 2 4 5 6 7 8]


In [9]:
a = np.array([21, 43, 65, 88, 2, 9])
print(a)


a=np.sort(a)
print(a)

[21 43 65 88  2  9]
[ 2  9 21 43 65 88]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a=arr.ndim
print(arr) 
print("dimensions = ", a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimensions =  2


In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [12, 24, 36]]])
a=arr.ndim
b=arr.size
print(arr) 
print("dimensions = ", a)
print("size = ", b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [12 24 36]]]
dimensions =  3
size =  12


In [13]:
import numpy as np

a = np.array(49)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)
print("dimension= ", a.ndim)
print(b)
print("dimension= ", b.ndim)
print(c)
print("dimension= ", c.ndim)
print(d)
print("dimension= ", d.ndim)


49
dimension=  0
[1 2 3 4 5]
dimension=  1
[[1 2 3]
 [4 5 6]]
dimension=  2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimension=  3


In [14]:
import numpy as np

arr = np.array([[5, 6, 7, 8], [1, 2, 3, 4]])

print(arr.shape) 

(2, 4)


In [18]:
a = np.arange(6)
print(a)

b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
